---
title: "R Notebook"
output:
  pdf_document: default
  html_notebook: default
  html_document:
    df_print: paged
---


```{r}
library(tidyverse)
library(treemap)
library(fmsb)
```

```{r}
pokemon <- read.csv("pokemon.csv", header = T)
```

```{r}
#Treemap Test
pokemon %>% 
  filter(Legendary == "True") %>%
  group_by(Type.1, Type.2) %>%
  count() %>%
  treemap( index = c("Type.1", "Type.2"),
           vSize = "n" ,
           title = "Legendary by type",
           na.rm = T,
           na.color = T)
```
https://user-images.githubusercontent.com/68129414/174145967-25570c46-50fa-4ae6-96ce-7bed1142aa0f.png
```{r}
#Radar chart para un solo caso
pokemon_radar_chart <- select(pokemon, -X. ,-Type.1,-Type.2, -Total, -Generation, -Legendary)

rayquaza <- pokemon_radar_chart %>%
  filter(Name == "Rayquaza")

rayquaza <- select(rayquaza, -Name)

rayquaza <- rbind(rep(200,5), rep(0,5), rayquaza)

radarchart(rayquaza,
           pcol = rgb(0.35,0.162,0.49,0.9),
           pfcol=rgb(0.81,0.42,0.46,0.7) ,
           plwd=2,
           cglcol = "black",
           cglty = 1,
           vlcex = 0.8)


```
https://user-images.githubusercontent.com/68129414/174145987-b8f81044-8874-49d6-868e-6b76c2189fd1.png
```{r}
#radarchart para muchas variables
legendarios <- pokemon_radar_chart %>%
  filter(Name == "Rayquaza" | Name == "Kyogre" | Name == "Groudon")

rownames(legendarios) <- c("Kyogre", "Groudon", "Rayquaza")

legendarios <- select(legendarios, -Name)

legendarios <- rbind(rep(200,5), rep(0,5), legendarios)

colors_border=c( rgb(0.2,0.5,0.5,0.1), rgb(0.8,0.2,0.5,0.5) , rgb(0.7,0.5,0.1,0.9) )

colors_in=c( rgb(0.2,0.5,0.5,0.2), rgb(0.8,0.2,0.5,0.2) , rgb(0.7,0.5,0.1,0.2) )

radarchart(legendarios,
           pcol = colors_border,
           pfcol = colors_in,
           plwd = 1,
           plty = 2,
           cglcol = "black",
           caxislabels = seq(0,20,5))
legend(1.3,1,
       legend=c("Kyogre","Groudon", "Rayquaza"),
       col=c( rgb(0.2,0.5,0.5,0.2), rgb(0.8,0.2,0.5,0.2) , rgb(0.7,0.5,0.1,0.2) ),
       lty=c(1,2))
```
https://user-images.githubusercontent.com/68129414/174145999-106a7732-0c72-4695-a1d6-3d0ce48d7116.png
